### ISSUE TITLE
Kubernetes support is in progress

### ISSUE THREAD

**Issue by hrichardlee** [meadowdata/meadowrun#124]
Potential improvements to take Kubernetes support from "prototype" to "v1.0":
- Options for deploying code/the environment:
  - [x] A pre-built container image with Deployment.container_image
  - [x] Local code and interpreter with [Deployment.mirror_local](https://docs.meadowrun.io/en/stable/reference/apis/#meadowrun.run_job.Deployment.mirror_local). Done in #146
  - [x] Code/interpreter from a git repo/an interpreter spec file [Deployment.git_repo](https://docs.meadowrun.io/en/stable/reference/apis/#meadowrun.run_job.Deployment.git_repo). Done in #152
    - [x] Exception: specifying a custom container with a git repo is not supported yet. Done in #201
    - [x] Exception: running a command with a CodeZipFile and a user-specified container does not work. Done in #201 
  - [ ] Apt dependencies (additional_software) are not supported
  - [ ] Sidecar containers are not supported
- There is some generally unsupported functionality
  - [x] Support for specifying resource requirements. Done in #146
  - [x] Support for opening ports. Done in #146
  - [ ] GPUs are not supported
- There are a lot of different ways to transfer inputs/outputs back and forth from containers:
  - [x] Require an S3-compatible object store
  - [ ] Support actual S3/Azure Storage when running in EKS/AKS
  - [ ] Require an NFS volumes
  - [ ] Use ConfigMap (1MB limit)
  - [ ] Investigate having a sidecar container running sshd + port forwarding + a shared volume
- There are a lot of different ways to allocate tasks to workers in run_map:
  - [x] Use pre-destined round-robin (doesn't work well when tasks are different sizes)
  - [ ] Require an SQS-compatible queue, e.g. SQS itself or elasticmq
  - [ ] Start our own queue in a pod (difficulty is making it accessible from outside of Kubernetes)
  - [ ] Require other types of queues (RabbitMQ, Kafka)

**Comment by hrichardlee** [comment]
Declaring initial version of Kubernetes support done. Remaining items will be tracked in #217
