### ISSUE TITLE
Finish support for Kubernetes with reusable pods

### ISSUE THREAD

**Issue by hrichardlee** [meadowdata/meadowrun#186]
Initial support was started in #187 
- [x] Don't reuse pods if they're already running another job (plan is to use the Ready status on containers) #190 
- [x] Handle errors setting up the job (i.e. right now we don't poll for `process_state` uploads) 3d67c1b
- [x] Support ports and resources eb1efe8
- [ ] Implement `wait_for_result` options
- [x] Support custom container images #201
- [x] Support run_function and run_command #201

**Comment by hrichardlee** [comment]
Declaring initial version of resuable pods in Kubernetes done. Remaining item will be tracked in https://github.com/meadowdata/meadowrun/issues/217
